class Productos {
  static productos = [
    {
      Id: 1,
      Nombre: 'Botines Mercurial Vapor 14',
      Precio: 380000.00,
      Tipo: 'Calzado',
      Descripcion: 'Botines Nike Mercurial Vapor 14 Academy Fg/Mg',
      srcImage: 'https://i.ibb.co/4g2kGgY/Mercurial-vapor-14.jpg',
    },
    {
      Id: 2,
      Nombre: 'Camiseta Talleres',
      Precio: 120000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Camiseta de futbol Talleres Gigova',
      srcImage: 'https://i.ibb.co/vYfBSgb/camiseta-gv-tall-2021-arquero-alternativa-fc-ng-nino-11-dfc34f2f22997b028216304172964245-1024-1024.jpg',
    },
    {
      Id: 3,
      Nombre: 'Botines Mercurial Vapor 13',
      Precio: 290000.00,
      Tipo: 'Calzado',
      Descripcion: 'Botines de futbol Nike Mercurial Vapor 13 Academy FG/MG',
      srcImage: 'https://i.ibb.co/30zmCM9/botines-de-futbol-nike-mercurial-vapor-13-academy-fg-mg-ni-o-gris-510010at8123906-1.jpg',
    },
    {
      Id: 4,
      Nombre: 'Camiseta San Lorenzo',
      Precio: 120000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Camiseta de futbol Nike San Lorenzo 2023',
      srcImage: 'https://i.ibb.co/2dJ0b9L/san-lorenzo-camiseta.webp',
    },
    {
      Id: 5,
      Nombre: 'Short Boca Juniors',
      Precio: 90000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Short de futbol Adidas Boca Juniors 2022',
      srcImage: 'https://i.ibb.co/VMswmxD/short-de-futbol-adidas-boca-juniors-downtime-azul-100020gl7507001-1.jpg',
    },
    {
      Id: 6,
      Nombre: 'Short Dribbling',
      Precio: 65000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Short Dribbling blanco liso',
      srcImage: 'https://i.ibb.co/JHwkCSW/DGDFIFSM001-WK-1.jpg',
    },
    {
      Id: 7,
      Nombre: 'Botines Nike Mercurial Superfly 7',
      Precio: 250000.00,
      Tipo: 'Calzado',
      Descripcion: 'BOTINES DE FUTBOL NIKE MERCURIAL SUPERFLY 7 ACADEMY FG NIÑO NEGRO',
      srcImage: 'https://i.ibb.co/ZBMVhT4/botines-de-futbol-nike-mercurial-superfly-7-academy-fg-ni-o-negro-510010at8120001-1.jpg',
    },
    {
      Id: 8,
      Nombre: 'Botines Nike Phantom GT2',
      Precio: 400000.00,
      Tipo: 'Calzado',
      Descripcion: 'Botines Nike Phantom Gt2 Elite SG Pro',
      srcImage: 'https://i.ibb.co/D7dpgdN/DJ8040809-A.webp',
    },
    {
      Id: 9,
      Nombre: 'Camiseta Seleccion Argentina',
      Precio: 140000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Camiseta de futbol Seleccion Argentina Adidas Qatar 2022',
      srcImage: 'https://i.ibb.co/rHLRdks/IB3592-A.webp',
    },
    {
      Id: 10,
      Nombre: 'Botines Nike Legend 8',
      Precio: 200000.00,
      Tipo: 'Calzado',
      Descripcion: 'Botines Nike Legend 8 Academy FG/MG Jr',
      srcImage: 'https://i.ibb.co/k5H4YnQ/NI-AT5732-104-1.jpg',
    },
    {
      Id: 11,
      Nombre: 'Camiseta de Francia 1995',
      Precio: 200000.00,
      Tipo: 'Vestimenta',
      Descripcion: 'Camiseta de futbol retro Francia Eurocopa 199',
      srcImage: 'https://i.ibb.co/19wV0dC/D-NQ-NP-871698-MLA49191367227-022022-O.webp',
    },
    {
      Id: 12,
      Nombre: 'BOTINES NIKE SUPERFLY 7',
      Precio: 336000.00,
      Tipo: 'Calzado',
      Descripcion: 'BOTINES DE FUTBOL 5 NIKE SUPERFLY 7 ELITE TF',
      srcImage: 'https://i.ibb.co/bgpx2kf/botines-de-futbol-nike-superfly-7-elite-tf-at7981-6061-fafc3b3bffe0d1db4916307963611583-640-0.jpg',
    },
  ];
}

export default Productos;